version: '3.8'

services:
  flare-bypasser:
    image: ghcr.io/yoori/flare-bypasser:latest
    container_name: flare-bypasser
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
      - LOG_HTML=false
      - HEADLESS=true
    restart: unless-stopped 