version: "3.8"

services:
  flare-bypasser:
    image: ghcr.io/yoori/flare-bypasser:latest
    container_name: flare-bypasser
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=DEBUG
      - LOG_HTML=true
      - HEADLESS=false
      - USE_UNDETECTED_CHROMEDRIVER=true
      - NO_SANDBOX=true
    restart: unless-stopped
